
package vista;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.*;
/**
 *
 * @author freid
 */
public class jPanelInfoProd extends javax.swing.JPanel {

    private clsTienda objTienda;
    
    public jPanelInfoProd(clsTienda objTienda) {
        this.objTienda = objTienda;
        initComponents();
        btnBuscar.setEnabled(false);
    }

    public void botonBuscar(){
        if(txtCodigoBarras.getText().isEmpty()){
            btnBuscar.setEnabled(false);
        }else{
            btnBuscar.setEnabled(true);
        }
    }
    
    public int buscarProducto(){
        int posicion=-1;
        long codigo = Long.parseLong(this.txtCodigoBarras.getText());
        
        for(int i=0;i<this.objTienda.getLstProductos().size();i++){
            if(codigo == this.objTienda.getLstProductos().get(i).getCodigoBarras()){
                posicion=i;
                break;
            }
        }
        
        return posicion;
    }
    
    public void datosProducto(int posicion){
        SimpleDateFormat formatoFV = new SimpleDateFormat("dd/MM/YYY");
            String fechaVen = formatoFV.format(this.objTienda.getLstProductos().
                get(posicion).getFechaVen().getTime());

        SimpleDateFormat formatoFB = new SimpleDateFormat("dd/MM/YYY");
        String fechaFab = formatoFB.format(this.objTienda.getLstProductos().
               get(posicion).getFechaFab().getTime());

        Object matrizProd [][] = new Object[1][5];

        matrizProd[0][0]=this.objTienda.getLstProductos().get(posicion).getCodigoBarras();
        matrizProd[0][1]=this.objTienda.getLstProductos().get(posicion).getNombre();
        matrizProd[0][2]=fechaVen;
        matrizProd[0][3]=fechaFab;
        matrizProd[0][4]=this.objTienda.getLstProductos().get(posicion).getPrecio();

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            matrizProd, 
            new String [] {
                "Nombre", "Codigo", "Fecha Vencimiento", "Fecha Fabricación", "Precio"
            } 
        ));
    }
    
    public void datosIngredientes(int posicion){
        Object matrizIng [][] = new Object[this.objTienda.getLstProductos().
                    get(posicion).getLstIngredientes().size()][3];

        int tamanio;
        tamanio= this.objTienda.getLstProductos().get(posicion).getLstIngredientes().size();

        for(int i=0;i<tamanio;i++){
            matrizIng[i][0]=this.objTienda.getLstProductos().get(posicion).
                    getLstIngredientes().get(i).getNombre();
            matrizIng[i][1]=this.objTienda.getLstProductos().get(posicion).
                    getLstIngredientes().get(i).getUnidad();
            matrizIng[i][2]=this.objTienda.getLstProductos().get(posicion).
                    getLstIngredientes().get(i).getValor();
        }

        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            matrizIng,
            new String [] {"Nombre", "Unidad", "Valor"}
        ));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        spContenedorProd = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        spContenedorIng = new javax.swing.JScrollPane();
        tablaIngredientes = new javax.swing.JTable();
        lblTituloIng = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("INFORMACIÓN PRODUCTOS");
        jPanelSuperior.add(lblTitulo);

        add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        lblCodigoBarras.setText("Digite Código De Barras:");

        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyTyped(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Fecha Vencimiento", "Fecha Fabricación", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setEnabled(false);
        spContenedorProd.setViewportView(tablaProductos);

        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Unidad", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaIngredientes.setEnabled(false);
        spContenedorIng.setViewportView(tablaIngredientes);

        lblTituloIng.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTituloIng.setText("INGREDIENTES");

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCentroLayout.createSequentialGroup()
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spContenedorIng))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spContenedorProd))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCentroLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblCodigoBarras)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(35, 35, 35))
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloIng)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(spContenedorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloIng)
                .addGap(18, 18, 18)
                .addComponent(spContenedorIng, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        add(jPanelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int posicion = buscarProducto();
        
        if(posicion==-1){
            JOptionPane.showMessageDialog(this, "Producto No Registrado En La Tienda",
                    "Busqueda",JOptionPane.ERROR_MESSAGE);
        }else{
            datosProducto(posicion);
            datosIngredientes(posicion);
            this.txtCodigoBarras.setText("");
            this.btnBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        botonBuscar();
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void txtCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar Solo Números");
        }
    }//GEN-LAST:event_txtCodigoBarrasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloIng;
    private javax.swing.JScrollPane spContenedorIng;
    private javax.swing.JScrollPane spContenedorProd;
    private javax.swing.JTable tablaIngredientes;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCodigoBarras;
    // End of variables declaration//GEN-END:variables
}
