
package vista;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author freid
 */
public class jPanelRegProd extends javax.swing.JPanel {

    private ArrayList<clsProducto> lstProductos;
    private clsTienda objTienda;
    
    public jPanelRegProd(ArrayList<clsProducto> lstProductos, clsTienda objTienda) {
        this.lstProductos = lstProductos;
        this.objTienda = objTienda;
        initComponents();
        btnBuscar.setEnabled(false);
    }

    public void botonBuscar(){
        if(txtCodigoBarras.getText().isEmpty()){
            btnBuscar.setEnabled(false);
        }else{
            btnBuscar.setEnabled(true);
        }
        
    }
    
    public int buscarProducto(){
        int posicion=-1;
        long codigo = Long.parseLong(this.txtCodigoBarras.getText());
        
        for(int i=0;i<this.lstProductos.size();i++){
            if(codigo == this.lstProductos.get(i).getCodigoBarras()){
                posicion=i;
                break;
            }
        }
        
        return posicion;
    }
    
     public void datosProducto(int posicion){
        SimpleDateFormat formatoFV = new SimpleDateFormat("dd/MM/YYY");
            String fechaVen = formatoFV.format(this.lstProductos.
                get(posicion).getFechaVen().getTime());

        SimpleDateFormat formatoFB = new SimpleDateFormat("dd/MM/YYY");
        String fechaFab = formatoFB.format(this.lstProductos.
               get(posicion).getFechaFab().getTime());

        Object matrizProd [][] = new Object[1][5];

        matrizProd[0][0]=this.lstProductos.get(posicion).getCodigoBarras();
        matrizProd[0][1]=this.lstProductos.get(posicion).getNombre();
        matrizProd[0][2]=fechaVen;
        matrizProd[0][3]=fechaFab;
        matrizProd[0][4]=this.lstProductos.get(posicion).getPrecio();

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            matrizProd, 
            new String [] {
                "Codigo", "Nombre", "Fecha Vencimiento", "Fecha Fabricación", "Precio"
            } 
        ));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        spContenedor = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("REGISTRAR PRODUCTOS");
        jPanelSuperior.add(lblTitulo);

        add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        lblCodigoBarras.setText("Digite Código De Barras:");

        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyTyped(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        spContenedor.setEnabled(false);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Fecha Vencimiento", "Fecha Fabricación", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spContenedor.setViewportView(tablaProductos);

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanelCentroLayout.createSequentialGroup()
                                .addComponent(lblCodigoBarras)
                                .addGap(38, 38, 38)
                                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(spContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(jPanelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int posicion = buscarProducto();
        
        if(posicion==-1){
            JOptionPane.showMessageDialog(this, "Producto No Encontrado","Busqueda"
                    ,JOptionPane.ERROR_MESSAGE);
        }else{
            datosProducto(posicion);
            this.btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int posicion = buscarProducto();
        
        clsProducto producto;
        producto = this.lstProductos.get(posicion);
        
        this.objTienda.agregarProducto(producto);
        JOptionPane.showMessageDialog(this, "Producto Registrado Con Éxito");
        this.txtCodigoBarras.setText("");
        this.btnRegistrar.setEnabled(false);

        this.btnBuscar.setEnabled(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        botonBuscar();
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void txtCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar Solo Números");
        }
    }//GEN-LAST:event_txtCodigoBarrasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane spContenedor;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCodigoBarras;
    // End of variables declaration//GEN-END:variables
}
