
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author freid
 */
public class jPanelCrearProd extends javax.swing.JPanel {

    private ArrayList<clsProducto> lstProductos;
    
    public jPanelCrearProd(ArrayList<clsProducto> lstProductos) {
        this.lstProductos = lstProductos;
        initComponents();
    }

    public clsProducto crearProducto(){
        clsProducto objProducto = new clsProducto();
        
        objProducto.setCodigoBarras(Long.parseLong(this.txtCodigoBarras.getText()));
        objProducto.setNombre(this.txtNombre.getText());
        objProducto.setFechaVen(this.dcFechaVen.getCalendar());
        objProducto.setFechaFab(this.dcFechaFab.getCalendar());
        objProducto.setPrecio(Double.parseDouble(this.txtPrecio.getText()));
        
        return objProducto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        lblCodigoBarras = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFechaVen = new javax.swing.JLabel();
        lblFechaFab = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        txtCodigoBarras = new javax.swing.JTextField();
        dcFechaVen = new com.toedter.calendar.JDateChooser();
        dcFechaFab = new com.toedter.calendar.JDateChooser();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lbl$ = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("CREAR PRODUCTOS");
        jPanelSuperior.add(lblTitulo);

        add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        lblCodigoBarras.setText("Digite Código De Barras:");

        lblNombre.setText("Escriba El Nombre:");

        lblFechaVen.setText("Seleccione Fecha Vencimiento:");

        lblFechaFab.setText("Seleccione Fecha Fabricación:");

        lblPrecio.setText("Digite El Precio:");

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyTyped(evt);
            }
        });

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        lbl$.setText("$");

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(lbl$)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addComponent(lblCodigoBarras)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaVen)
                            .addComponent(lblFechaFab))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcFechaVen, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(dcFechaFab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaVen)
                    .addComponent(dcFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFab)
                    .addComponent(dcFechaFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lbl$)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if(this.txtCodigoBarras.getText().isEmpty() || this.txtNombre.getText().isEmpty()
                || this.dcFechaVen.getDate() == null|| this.dcFechaFab.getDate() == null
                || this.txtPrecio.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Diligenciar todos los campos"
                    , "Validacion",JOptionPane.ERROR_MESSAGE);
            
        }else{
            clsProducto objProducto = crearProducto();
            
            this.lstProductos.add(objProducto);
            JOptionPane.showMessageDialog(this,"Producto Creado con Éxito!!!");
            this.txtCodigoBarras.setText("");
            this.txtNombre.setText("");
            this.dcFechaVen.setCalendar(null);
            this.dcFechaFab.setCalendar(null);
            this.txtPrecio.setText("");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtCodigoBarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar Solo Números");
        }
    }//GEN-LAST:event_txtCodigoBarrasKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar Solo Números");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private com.toedter.calendar.JDateChooser dcFechaFab;
    private com.toedter.calendar.JDateChooser dcFechaVen;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lbl$;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblFechaFab;
    private javax.swing.JLabel lblFechaVen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
