
package vista;

import java.awt.BorderLayout;
import java.util.ArrayList;
import modelo.*;

/**
 *
 * @author freid
 */
public class vtnPrincipal extends javax.swing.JFrame {

    private jPanelCrearProd panelCrearProd;
    private jPanelCrearIng panelCrearIng;
    private jPanelRegProd panelRegProd;
    private jPanelInfoProd panelInfoProd;
    private ArrayList<clsProducto> lstProductos;
    
    
    public vtnPrincipal() {
        this.lstProductos = new ArrayList<clsProducto>();
        clsTienda objTienda = new clsTienda("Justo y Bueno", "Popayan Cauca",
        321324524, "Popayan cauca");
        
        this.panelCrearProd = new jPanelCrearProd(this.lstProductos);
        this.panelCrearIng = new jPanelCrearIng(this.lstProductos);
        this.panelRegProd = new jPanelRegProd(this.lstProductos, objTienda);
        this.panelInfoProd = new jPanelInfoProd(objTienda);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelizquierdo = new javax.swing.JPanel();
        btnCrearProd = new javax.swing.JButton();
        btnCrearIng = new javax.swing.JButton();
        btnRegProd = new javax.swing.JButton();
        btnImprimirProd = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo.setText("GESTIÓN TIENDA JUSTO Y BUENO");
        jPanelSuperior.add(lblTitulo);

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanelizquierdo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCrearProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrearProd.setText("CREAR PRODUCTO");
        btnCrearProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProdActionPerformed(evt);
            }
        });

        btnCrearIng.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrearIng.setText("CREAR INGREDIENTE");
        btnCrearIng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearIng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearIngActionPerformed(evt);
            }
        });

        btnRegProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegProd.setText("REGISTRAR PRODUCTO");
        btnRegProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegProdActionPerformed(evt);
            }
        });

        btnImprimirProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimirProd.setText("INFORMACIÓN PRODUCTO");
        btnImprimirProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImprimirProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelizquierdoLayout = new javax.swing.GroupLayout(jPanelizquierdo);
        jPanelizquierdo.setLayout(jPanelizquierdoLayout);
        jPanelizquierdoLayout.setHorizontalGroup(
            jPanelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelizquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImprimirProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelizquierdoLayout.setVerticalGroup(
            jPanelizquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelizquierdoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCrearProd)
                .addGap(32, 32, 32)
                .addComponent(btnCrearIng)
                .addGap(30, 30, 30)
                .addComponent(btnRegProd)
                .addGap(32, 32, 32)
                .addComponent(btnImprimirProd)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelizquierdo, java.awt.BorderLayout.LINE_START);

        jPanelCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCentro.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProdActionPerformed
        this.jPanelCentro.remove(this.panelCrearIng);
        this.jPanelCentro.remove(this.panelRegProd);
        this.jPanelCentro.remove(this.panelInfoProd);
        this.jPanelCentro.add(this.panelCrearProd,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearProdActionPerformed

    private void btnCrearIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearIngActionPerformed
        this.jPanelCentro.remove(this.panelCrearProd);
        this.jPanelCentro.remove(this.panelRegProd);
        this.jPanelCentro.remove(this.panelInfoProd);
        this.jPanelCentro.add(this.panelCrearIng,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnCrearIngActionPerformed

    private void btnRegProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProdActionPerformed
        this.jPanelCentro.remove(this.panelCrearProd);
        this.jPanelCentro.remove(this.panelCrearIng);
        this.jPanelCentro.remove(this.panelInfoProd);
        this.jPanelCentro.add(this.panelRegProd,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnRegProdActionPerformed

    private void btnImprimirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirProdActionPerformed
        this.jPanelCentro.remove(this.panelCrearProd);
        this.jPanelCentro.remove(this.panelCrearIng);
        this.jPanelCentro.remove(this.panelRegProd);
        this.jPanelCentro.add(this.panelInfoProd,BorderLayout.CENTER);
        this.jPanelCentro.revalidate();
        this.jPanelCentro.repaint();
    }//GEN-LAST:event_btnImprimirProdActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearIng;
    private javax.swing.JButton btnCrearProd;
    private javax.swing.JButton btnImprimirProd;
    private javax.swing.JButton btnRegProd;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanelizquierdo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
